# --- Site Settings ---
title: DePrince Lab
description: "Quantum Chemistry Method Development and Simulations"

logo: "/images/deprince_group_logo.png"

# --- URL Settings ---
# The absolute base hostname
url: "https://www.chem.fsu.edu"

# The path that comes AFTER the domain
baseurl: "/~deprince"

# --- Build Settings ---
remote_theme: vfvong/jekyll-theme-tao

plugins:
  - jekyll-remote-theme
  - jekyll-paginate

# --- Pagination Settings (Required by Tao theme) ---
paginate: 5
paginate_path: "/page:num/"

# --- Markdown Settings ---
markdown: kramdown
highlighter: rouge
