plugins:
  - jekyll-remote-theme
  
remote_theme: vfvong/jekyll-theme-tao

#plugins:
#  - jekyll-paginate

#paginate: 2

title: DePrince Lab
#description: Quantum Chemistry Method Development and Simulations
