#!/bin/bash

for name in qm_postulates translation vibration rotation hydrogen variation perturbation hartree_fock second_quantization cis; do
    file=${name}/${name}.html
    ./replace 'autoNumber: "AMS",' "" ${file}
    ./replace "--jp-cell-prompt-width: 64px;" "--jp-cell-prompt-width: 0px;" ${file}
    ./replace "--jp-ui-font-size1: 13px;" "--jp-ui-font-size1: 18px;" ${file}
    ./replace "--jp-content-font-size1: 14px;" "--jp-content-font-size1: 16px;" ${file}
    ./replace "--jp-code-font-size: 13px;" "--jp-code-font-size: 12px;" ${file}
done
